"""Add terms_conditions to quotations

Revision ID: 0d5edb560e2c
Revises: 6b891596c689
Create Date: 2026-07-01 22:28:49.846697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d5edb560e2c'
down_revision = '6b891596c689'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quotations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('terms_conditions', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quotations', schema=None) as batch_op:
        batch_op.drop_column('terms_conditions')

    # ### end Alembic commands ###
