"""add payment mode to invoice

Revision ID: 44cdf5f82b43
Revises: f1739b983511
Create Date: 2026-07-03 20:23:30.245421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44cdf5f82b43'
down_revision = 'f1739b983511'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_mode', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_column('payment_mode')

    # ### end Alembic commands ###
