"""tenant-scope items: composite unique constraints on item_code, sku, barcode

Revision ID: 5122c47cf4b0
Revises: d86f5ceb56a2
Create Date: 2026-07-22 17:30:02.801195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5122c47cf4b0'
down_revision = 'd86f5ceb56a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('barcode'))
        batch_op.drop_index(batch_op.f('ix_items_item_code'))
        batch_op.create_index(batch_op.f('ix_items_item_code'), ['item_code'], unique=False)
        batch_op.drop_index(batch_op.f('ix_items_sku'))
        batch_op.create_index(batch_op.f('ix_items_sku'), ['sku'], unique=False)
        batch_op.create_unique_constraint('uq_item_tenant_barcode', ['tenant_id', 'barcode'])
        batch_op.create_unique_constraint('uq_item_tenant_item_code', ['tenant_id', 'item_code'])
        batch_op.create_unique_constraint('uq_item_tenant_sku', ['tenant_id', 'sku'])
        batch_op.drop_constraint(batch_op.f('items_ibfk_5'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('items_ibfk_5'), 'tenants', ['tenant_id'], ['id'])
        batch_op.drop_constraint('uq_item_tenant_sku', type_='unique')
        batch_op.drop_constraint('uq_item_tenant_item_code', type_='unique')
        batch_op.drop_constraint('uq_item_tenant_barcode', type_='unique')
        batch_op.drop_index(batch_op.f('ix_items_sku'))
        batch_op.create_index(batch_op.f('ix_items_sku'), ['sku'], unique=True)
        batch_op.drop_index(batch_op.f('ix_items_item_code'))
        batch_op.create_index(batch_op.f('ix_items_item_code'), ['item_code'], unique=True)
        batch_op.create_index(batch_op.f('barcode'), ['barcode'], unique=True)

    # ### end Alembic commands ###
