"""add branch_id to all modules

Revision ID: 6e8c5dc74d29
Revises: 49a620a817d9
Create Date: 2026-07-09 12:04:56.452170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e8c5dc74d29'
down_revision = '49a620a817d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('branch_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'branches', ['branch_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('deposits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('branch_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'branches', ['branch_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('expense_categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('branch_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'branches', ['branch_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('branch_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'branches', ['branch_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('money_transfers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('branch_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'branches', ['branch_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('purchase_returns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('branch_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'branches', ['branch_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('branch_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'branches', ['branch_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('quotations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('branch_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'branches', ['branch_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('stock_adjustments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('branch_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'branches', ['branch_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('stock_transfers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('branch_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'branches', ['branch_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('warehouses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('branch_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'branches', ['branch_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('warehouses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('branch_id')

    with op.batch_alter_table('stock_transfers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('branch_id')

    with op.batch_alter_table('stock_adjustments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('branch_id')

    with op.batch_alter_table('quotations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('branch_id')

    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('branch_id')

    with op.batch_alter_table('purchase_returns', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('branch_id')

    with op.batch_alter_table('money_transfers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('branch_id')

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('branch_id')

    with op.batch_alter_table('expense_categories', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('branch_id')

    with op.batch_alter_table('deposits', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('branch_id')

    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('branch_id')

    # ### end Alembic commands ###
