"""Create items tables

Revision ID: 8b7decd6e128
Revises: 44cdf5f82b43
Create Date: 2026-07-04 16:40:30.217438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b7decd6e128'
down_revision = '44cdf5f82b43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_brand_tenant_name')
    )
    with op.batch_alter_table('brands', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_brands_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_category_tenant_name')
    )
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categories_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('item_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_item_group_tenant_name')
    )
    with op.batch_alter_table('item_groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_item_groups_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('taxes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('tax_value', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_tax_tenant_name')
    )
    with op.batch_alter_table('taxes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_taxes_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('short_name', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_unit_tenant_name')
    )
    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_units_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_code', sa.String(length=50), nullable=False),
    sa.Column('item_name', sa.String(length=255), nullable=False),
    sa.Column('item_group_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('brand_id', sa.Integer(), nullable=True),
    sa.Column('unit_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('hsn', sa.String(length=50), nullable=True),
    sa.Column('sac', sa.String(length=50), nullable=True),
    sa.Column('barcode', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('price_expenses', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('purchase_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('sales_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('mrp', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('discount_type', sa.String(length=20), nullable=True),
    sa.Column('discount_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('tax_id', sa.Integer(), nullable=True),
    sa.Column('tax_type', sa.String(length=20), nullable=True),
    sa.Column('warehouse_id', sa.Integer(), nullable=True),
    sa.Column('opening_stock', sa.Integer(), nullable=True),
    sa.Column('alert_quantity', sa.Integer(), nullable=True),
    sa.Column('profit_margin', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('seller_points', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['item_group_id'], ['item_groups.id'], ),
    sa.ForeignKeyConstraint(['tax_id'], ['taxes.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('barcode')
    )
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_items_item_code'), ['item_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_items_item_name'), ['item_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_items_sku'), ['sku'], unique=False)
        batch_op.create_index(batch_op.f('ix_items_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_items_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_items_sku'))
        batch_op.drop_index(batch_op.f('ix_items_item_name'))
        batch_op.drop_index(batch_op.f('ix_items_item_code'))

    op.drop_table('items')
    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_units_tenant_id'))

    op.drop_table('units')
    with op.batch_alter_table('taxes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_taxes_tenant_id'))

    op.drop_table('taxes')
    with op.batch_alter_table('item_groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_item_groups_tenant_id'))

    op.drop_table('item_groups')
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categories_tenant_id'))

    op.drop_table('categories')
    with op.batch_alter_table('brands', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_brands_tenant_id'))

    op.drop_table('brands')
    # ### end Alembic commands ###
