"""refactor_product_to_item

Revision ID: 9e33ddbe3260
Revises: eae09e35c73a
Create Date: 2026-07-14 13:00:20.756346

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9e33ddbe3260'
down_revision = 'eae09e35c73a'
branch_labels = None
depends_on = None


def upgrade():
    # 1. Drop foreign keys referencing `products` table first
    with op.batch_alter_table('invoice_items', schema=None) as batch_op:
        batch_op.drop_constraint('invoice_items_ibfk_2', type_='foreignkey')
        
    with op.batch_alter_table('purchase_items', schema=None) as batch_op:
        batch_op.drop_constraint('purchase_items_ibfk_1', type_='foreignkey')

    with op.batch_alter_table('purchase_return_items', schema=None) as batch_op:
        batch_op.drop_constraint('purchase_return_items_ibfk_1', type_='foreignkey')

    with op.batch_alter_table('quotation_items', schema=None) as batch_op:
        batch_op.drop_constraint('quotation_items_ibfk_1', type_='foreignkey')

    # 2. Now safe to drop `products` table
    op.drop_table('products')

    # 3. Add `item_id` column, set up foreign keys to `items`, and drop `product_id`
    with op.batch_alter_table('invoice_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'items', ['item_id'], ['id'])
        batch_op.drop_column('product_id')

    with op.batch_alter_table('purchase_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'items', ['item_id'], ['id'])
        batch_op.drop_column('product_id')

    with op.batch_alter_table('purchase_return_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'items', ['item_id'], ['id'])
        batch_op.drop_column('product_id')

    with op.batch_alter_table('quotation_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'items', ['item_id'], ['id'])
        batch_op.drop_column('product_id')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quotation_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('quotation_items_ibfk_1'), 'products', ['product_id'], ['id'])
        batch_op.drop_column('item_id')

    with op.batch_alter_table('purchase_return_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('purchase_return_items_ibfk_1'), 'products', ['product_id'], ['id'])
        batch_op.drop_column('item_id')

    with op.batch_alter_table('purchase_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('purchase_items_ibfk_1'), 'products', ['product_id'], ['id'])
        batch_op.drop_column('item_id')

    with op.batch_alter_table('invoice_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('invoice_items_ibfk_2'), 'products', ['product_id'], ['id'])
        batch_op.drop_column('item_id')

    op.create_table('products',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=150), nullable=False),
    sa.Column('sku', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=60), nullable=True),
    sa.Column('description', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('unit_price', mysql.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('tax_rate', mysql.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('stock_quantity', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('unit', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('tenant_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('branch_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('products_ibfk_2'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('products_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###
