"""add branch_id to items, scope item_code/sku/barcode uniqueness per branch

Revision ID: a7c680989100
Revises: 971ecb150379
Create Date: 2026-08-03 15:19:22.236630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7c680989100'
down_revision = '971ecb150379'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('branch_id', sa.Integer(), nullable=True))
        batch_op.drop_index(batch_op.f('uq_item_tenant_barcode'))
        batch_op.drop_index(batch_op.f('uq_item_tenant_item_code'))
        batch_op.drop_index(batch_op.f('uq_item_tenant_sku'))
        batch_op.create_index(batch_op.f('ix_items_branch_id'), ['branch_id'], unique=False)
        batch_op.create_foreign_key(None, 'branches', ['branch_id'], ['id'], ondelete='SET NULL')

    # Backfill branch_id from each item's existing warehouse -- items.branch_id
    # is new and starts NULL for every row, but items that already have a
    # warehouse assigned already have a real branch via that warehouse.
    op.execute(
        """
        UPDATE items
        JOIN warehouses ON items.warehouse_id = warehouses.id
        SET items.branch_id = warehouses.branch_id
        WHERE warehouses.branch_id IS NOT NULL
        """
    )

    # Unique constraints added only after the backfill, so the backfill
    # itself can't trip over them (e.g. two legacy items already sharing an
    # item_code, both about to land in the same branch).
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_item_tenant_branch_barcode', ['tenant_id', 'branch_id', 'barcode'])
        batch_op.create_unique_constraint('uq_item_tenant_branch_item_code', ['tenant_id', 'branch_id', 'item_code'])
        batch_op.create_unique_constraint('uq_item_tenant_branch_sku', ['tenant_id', 'branch_id', 'sku'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('uq_item_tenant_branch_sku', type_='unique')
        batch_op.drop_constraint('uq_item_tenant_branch_item_code', type_='unique')
        batch_op.drop_constraint('uq_item_tenant_branch_barcode', type_='unique')
        batch_op.drop_index(batch_op.f('ix_items_branch_id'))
        batch_op.create_index(batch_op.f('uq_item_tenant_sku'), ['tenant_id', 'sku'], unique=True)
        batch_op.create_index(batch_op.f('uq_item_tenant_item_code'), ['tenant_id', 'item_code'], unique=True)
        batch_op.create_index(batch_op.f('uq_item_tenant_barcode'), ['tenant_id', 'barcode'], unique=True)
        batch_op.drop_column('branch_id')

    # ### end Alembic commands ###
