"""add branch_id to categories and brands, scope name uniqueness per branch

Revision ID: ccfe70a01441
Revises: a7c680989100
Create Date: 2026-08-04 11:31:59.108906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccfe70a01441'
down_revision = 'a7c680989100'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('brands', schema=None) as batch_op:
        batch_op.add_column(sa.Column('branch_id', sa.Integer(), nullable=True))
        batch_op.drop_index(batch_op.f('uq_brand_tenant_name'))
        batch_op.create_index(batch_op.f('ix_brands_branch_id'), ['branch_id'], unique=False)
        batch_op.create_foreign_key(None, 'branches', ['branch_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('branch_id', sa.Integer(), nullable=True))
        batch_op.drop_index(batch_op.f('uq_category_tenant_name'))
        batch_op.create_index(batch_op.f('ix_categories_branch_id'), ['branch_id'], unique=False)
        batch_op.create_foreign_key(None, 'branches', ['branch_id'], ['id'], ondelete='SET NULL')

    # Backfill: existing brands/categories predate this per-branch model, so
    # assign them to each tenant's earliest active branch (the one that
    # existed before multi-branch was introduced) rather than leaving them
    # branch_id=NULL, which would make them invisible everywhere once branch
    # filtering goes into effect. Mirrors the same backfill approach used for
    # items.branch_id and the earlier cleanup_orphan_branch_data.py script.
    op.execute(
        """
        UPDATE brands b
        JOIN (
            SELECT tenant_id, MIN(id) AS branch_id
            FROM branches
            WHERE is_active = 1
            GROUP BY tenant_id
        ) fb ON b.tenant_id = fb.tenant_id
        SET b.branch_id = fb.branch_id
        WHERE b.branch_id IS NULL
        """
    )
    op.execute(
        """
        UPDATE categories c
        JOIN (
            SELECT tenant_id, MIN(id) AS branch_id
            FROM branches
            WHERE is_active = 1
            GROUP BY tenant_id
        ) fb ON c.tenant_id = fb.tenant_id
        SET c.branch_id = fb.branch_id
        WHERE c.branch_id IS NULL
        """
    )

    # Unique constraints added only after the backfill so it can't trip over
    # them.
    with op.batch_alter_table('brands', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_brand_tenant_branch_name', ['tenant_id', 'branch_id', 'name'])
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_category_tenant_branch_name', ['tenant_id', 'branch_id', 'name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('uq_category_tenant_branch_name', type_='unique')
        batch_op.drop_index(batch_op.f('ix_categories_branch_id'))
        batch_op.create_index(batch_op.f('uq_category_tenant_name'), ['tenant_id', 'name'], unique=True)
        batch_op.drop_column('branch_id')

    with op.batch_alter_table('brands', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('uq_brand_tenant_branch_name', type_='unique')
        batch_op.drop_index(batch_op.f('ix_brands_branch_id'))
        batch_op.create_index(batch_op.f('uq_brand_tenant_name'), ['tenant_id', 'name'], unique=True)
        batch_op.drop_column('branch_id')

    # ### end Alembic commands ###
