"""add unique constraint on items.sku

Revision ID: d86f5ceb56a2
Revises: e509fe56f736
Create Date: 2026-07-21 18:04:45.892387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd86f5ceb56a2'
down_revision = 'e509fe56f736'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_items_sku'))
        batch_op.create_index(batch_op.f('ix_items_sku'), ['sku'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_items_sku'))
        batch_op.create_index(batch_op.f('ix_items_sku'), ['sku'], unique=False)

    # ### end Alembic commands ###
