"""add quotation conversion link and cgst sgst igst split columns

Revision ID: e509fe56f736
Revises: 9e33ddbe3260
Create Date: 2026-07-21 12:44:11.597164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e509fe56f736'
down_revision = '9e33ddbe3260'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('line_cgst', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('line_sgst', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('line_igst', sa.Numeric(precision=12, scale=2), nullable=True))

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cgst_total', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('sgst_total', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('igst_total', sa.Numeric(precision=12, scale=2), nullable=True))

    with op.batch_alter_table('quotations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('converted_invoice_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'invoices', ['converted_invoice_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quotations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('converted_invoice_id')

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_column('igst_total')
        batch_op.drop_column('sgst_total')
        batch_op.drop_column('cgst_total')

    with op.batch_alter_table('invoice_items', schema=None) as batch_op:
        batch_op.drop_column('line_igst')
        batch_op.drop_column('line_sgst')
        batch_op.drop_column('line_cgst')

    # ### end Alembic commands ###
